<br>I.- Status of the "Diesel vs. Gasoline" Terms of Service
<br />-I.I.- These "Diesel vs. Gasoline" Terms of Service (hereinbefore and hereinafter the Terms) have been developed by the Site Administration and determine the terms of Site use and development conditions as well as the rights and obligations of its Users and Administration. The Terms cover also the relations regarding rights and interests of the third parties which are not Site Users but whose rights and interests may be affected as the result of Site Users’ actions.
<br />-I.II.- These Terms are the legally binding agreement between the User and the Site Administration whereby the Site Administration provides services for the User regarding use of the Site and its services (hereinafter the Services). In addition to these Terms, the agreement between the User and the Site Administration includes all special documents that regulate the provision of individual Site services and are posted in the relevant Site sections on the Internet.
<br />-I.III.- The User is obliged to be fully aware of these Terms before registering at the Site. The User’s registration at the Site means full and unconditional acceptance of these Terms by the User.
<br />-I.IV.- The Site Administration may make changes and/or additions to these Terms unilaterally without any special notification. These Terms are an open document accessible to the general public. The Site Administration recommends that the Users check the conditions of these Terms regularly for changes and/or additions. The continuation of use of the Site by the User after changes and/or additions are made to these Terms will mean the User’s agreement with and acceptance of such changes and/or additions.</p>

<br /><p>II.- Status of the "Diesel vs. Gasoline" Site
<br />-II.I.- The "Diesel vs. Gasoline" Site is a web resource and consists of an aggregate of information and software contained in the information system ensuring availability of such information on the Internet at: http://www.diesel-vs-gasoline.com.
<br />-II.II.- The Site Administration is the owner of all rights in the Site on the whole and all rights to use the web address (domain name) http://www.diesel-vs-gasoline.com. The Site Administration makes the Site available to all persons concerned in accordance with these Terms and effective legislation.
<br />-II.III.- These Terms establish conditions in accordance with which the rights to use information and intellectual activity results (including, without limitation, literary, musical, audio and visual works and sound records, graphic and design works, photo works, software) within individual sections of the Site may belong to the Site Users and other persons which have independently created and/or posted these items on the Site without direct participation of the Site Administration.</p>

<br /><p>III.- "Diesel vs. Gasoline" Site Administration
<br />-III.I.- In these Terms and other special documents, the "Diesel vs. Gasoline" Site Administration (hereinafter the Site Administration, Administration) is understood as "www.Diesel vs. Gasoline.com", a legal entity created under the laws of the Spain and registered at Spain, Guadalajara, c/Luis Ibarra Landete, 19004.
<br />-III.II.- The applications, suggestions and claims of individuals and legal entities to the Site Administration in connection with these Terms and all issues regarding the Site operation, infringement of rights and interests of third parties in the process of its use as well as the inquiries of the persons authorized by Spain. legislation may be sent to the mailing address of "www.Diesel vs. Gasoline.com" specified in clause -III.I.- hereof.
<br />-III.III.- As regards the Site operation and development, the Administration abides by effective Spanish legislation, these Terms and other special documents which were or may be developed and adopted by the Site Administration in order to regulate the provision of individual Site services to the Users.
<br />-III.IV.- No provisions of these Terms grant the User the right to use the brand name, trademarks, domain name or other distinctive marks of the Site Administration. The right to use the brand name, trademarks, domain names and other distinctive marks of the Site Administration may be granted only as agreed in writing with the Site Administration.</p>

<br /><p>IV.- Registration at the "Diesel vs. Gasoline" Site and the User’s Status
<br />-IV.I.- The User’s registration at the Site is free and voluntary and takes place at: http://www.diesel-vs-gasoline.com.
<br />-IV.II.- The Site User is the individual which is registered at the Site according to the procedure set by these Terms, reached the age acceptable in accordance with Spanish legislation for accepting these Terms, and has the relevant powers (hereinbefore and hereinafter the User).
<br />-IV.III.- When registering at the Site the User must provide the Site Administration with the necessary true and updated information to form the User’s personal page, including the User’s unique login (e-mail address or a combination of Latin letters and digits for entering the Site) and the password for access to the Site as well as the User’s first and last names. The User may be requested to provide additional information in the Site registration form.
<br />-IV.IV.- The User bears liability for ensuring that the information provided at the time of registration is true, up to date, complete, consistent with Spanish legislation and free from third parties’ claims.
<br />-IV.V.- After submitting the information specified in clause -IV.III.- hereof, the User has to complete a number of authentification procedures, namely: (a) confirm the registration by recognizing an automated text to tell computers and humans apart (CAPTCHA); (b) confirm his/her registration by activating the personal page via the message sent by the Site Administration to the User’s e-mail;. In case the whole sequence of the registration actions is completed successfully, the User’s personal page with the network address: http://www.diesel-vs-gasoline.com/user/perfil.php is created at the Site. including without limitation obscene words, names registered as trademarks (regardless of the MKTU class), brand names and commercial designations, unless the User is their exclusive owner. In case a breach of these conditions is detected, the Site Administration has the right to prohibit the User from using his/her sub-domain name and, among other things, transfer the right of its use to the appropriate person (representative of the right owner), if applicable. The User may register a maximum of one personal page at the Site.
<br />-IV.VI.- By registering the User accepts these Terms and assumes the rights and obligations thereunder regarding use and operation of the Site. The User acquires full rights to use the Site Services, provided that the personal page is more than thirty three per cent filled.
<br />-IV.VII.- After the successful registration of the User at the Site the Site Administration assumes the rights and obligations to the User as provided in these Terms.
<br />-IV.VIII.- By accepting these Terms through registration at the Site the User confirms his/her consent for the Site Administration to process his/her personal data submitted at registration as well as posted by the User voluntarily on his/her personal page. The User’s personal data are processed in accordance with Spanish legislation. The Site Administration processes the User’s personal data with the purpose of providing services for the User, including personalized (targeted) advertisements to the User; checking, examining and analyzing such data in order to maintain and improve the Site services and sections as well as to develop new Site services and sections. The Site Administration takes all necessary measures to protect the User’s personal data from unauthorized access, modification, disclosure or destruction. The Site Administration makes the User’s personal data available only to those employees, contractors and agents of the Site Administration which need this information to ensure the Ste operation and provision of Services to the User The information provided by the User, including personal data, may be used by the Site Administration to ensure compliance with the requirements of effective Spanish legislation (including in order to prevent and/or suppress unlawful and/or illegal actions of the User). The information provided by the User may be disclosed only in accordance with effective Spanish legislation on the demand of the court, law-enforcement bodies as well as in other cases as provided by Spanish legislation.
<br />-IV.IX.- The login and password chosen by the User are the necessary and sufficient information for the User’s access to the Site. The User does not have the right to transfer his/her login and password to third parties and bears full responsibility for their confidentiality, choosing himself / herself the method of their storage. Using his / her hardware and software the User may permit storage of the login and password (through cookies) for subsequent automatic authorization on the Site.
<br />-IV.X.- Unless the User proves otherwise, any actions taken with the use of his/her login and password are deemed to have been taken by the User. In case of unauthorized access to the User’s login and password and/or personal page or dissemination of the User’s login and password, the User is obliged to notify the Site Administration immediately according to the established procedure.
<br />-IV.XI.- After registration the User obtains the right to create, use and determine independently for personal non-commercial purposes the content of his/her own personal page and conditions for other Users’ access to its content as well as the ability to access and post information on the personal pages of other Users (subject to obtaining relevant access rights from their owners), use the "Diesel vs. Gasoline" social widgets on third-party sites without additional authorization. When the User uses social widgets, the User’s login and password as well as his/her data protected by the privacy settings are not transferred to third-party sites.
<br />-IV.XII.- As the owner of the information posted on his/her own personal page, the User understands that, except as provided by these Terms and effective Spanish legislation, the Site Administration does not participate in forming and using the content and controlling other users’ access to the User’s personal page.
<br />-IV.XIII.- Creation and use of Communities
<br />-IV.XIII.I.- The User has the right to create Communities (groups, official pages and meetings) to promote commercial, political, charitable and other organizations, brands, goods, works and/or services as well as various activities (hereinafter Objects of Promotion). The Objects of Promotion, methods and ways of promotion must meet effective Spanish legislation, including advertizing legislation, international legal acts, these Terms as well as accepted ethical rules and moral principles, including those belonging to such in the opinion of the Site Administration. The items specified in clauses III.I-III.V, III.IIX, III.X-III.XIV of the Advertisement Placement Rules may not be Objects of Promotion. In case of breach of these requirements the Site Administration has the right to block the Community or exclude the Community from the search system.
<br />-IV.XIII.II.- When creating and administering the Community, including in case of registration of the sub-domain name used for directing to the Community page, the User confirms that he/she acts on lawful grounds (e.g., on the basis of the power of attorney), has all necessary rights and his/her actions do not infringe the lawful rights and interests of third parties and effective Spanish legislation, including legislation on competition and rights to intellectual property results and means of individualization.
<br />-IV.XIII.III.- In case the User infringes the lawful rights and interests of third parties, effective Spanish legislation as well as the provisions hereof when creating and administering the Community, the Site Administration has the right to block the User’s access to the Community and/or transfer the administration rights for the Community as well as the right to use the registered sub-domain name to the lawful right owner which duly confirmed its rights in the Community Content, including the right in the means of individualization confusingly similar to the sub-domain name used in the Community.
<br />-IV.XIII.IV.- No outside commercial or political advertizing is allowed in the Community, including the description, main photo of the Community, pinned posts, news, discussions, surveys etc. A maximum of 3 (two) outside advertisements may be posted on the Community wall in a day. Outside advertizing is understood as any information which does not directly relate to the Community and the Object of Promotion, is disseminated in any form on behalf of the Community or other communities and users and is aimed at attracting the users’ attention to the advertized item, generating or maintaining interest to it. It is the responsibility of the User administering the Community to monitor and suppress the placement of outside advertizing in the Community, if such advertizing in breach of these Terms. A Community may be placed in the "Diesel vs. Gasoline" Site search system only subject to the requirements provided in this clause. In case of breach of these requirements the Site Administration has the right to exclude the Community from the search system.
<br />-IV.XIII.V.- All outside advertisements must meet clauses -I- and -III- of the "Diesel vs. Gasoline" Advertizing Placement Rules.
<br />-IV.XIII.IV.- The Site Administration may at its own discretion form and post the list of recommended Communities according to their information value for the users and other criteria. The recommended Communities are subject to additional limitations, maximum 1 (one) outside advertisement a week. In case this limitation is not complied with, the Site Administration has the right to exclude the Community from the list of recommended Communities.
<br />-IV.XIII.VII.- The User bears full liability for his/her actions connected with the creation and administration of Communities in accordance with effective Spanish legislation, international legal acts and these Terms.
<br />-IV.XIV.- In accordance with effective Spanish legislation the User has the right to revoke his/her consent for processing his/her personal data by: (a) removing independently the information posted previously by the User on the Site; (b) removing independently the User’s personal page using the “Remove Your Page” functionality available to the User in the “My Settings” section.</p>

<br /><p>V.- Obligations of the "Diesel vs. Gasoline" User
<br />-V.I.- When using the Site Services the User is obliged:
to comply with the provisions of effective Spanish legislation, these Terms and other special documents of the Site Administration;
to provide true, complete and up-to-date data at the time of registration and keep these data updated;
to inform the Site Administration of unauthorized access to the personal page and/or unauthorized access to and/or use of the User’s password and login;
not to provide other users with access to his/her own personal page or individual pieces of information on it, if it can involve breach of the Spanish legislation and/or these Terms, special documents of the Site Administration;
not to post on his/her personal page such information and objects (including links thereto) which may infringe the rights and interests of other persons;
before posting information and objects (including but limited to other people’s images, texts of various content, audio records and videos), to assess in advance whether such posting is lawful;
to keep confidential and not to disclose to other Users and third parties the personal data which became known to him/her as the result of communication with other Users and other use of the Site (including but not limited to home addresses, phone numbers, e-mail, ICQ addresses, passport details, banking information) and information on the private life of other users and third parties without the appropriate prior permission of the latter;
to make back-up copies of the information important for the User which is stored on his/her personal page.
<br />-V.II.- In case of doubts as to whether it is legal to take any actions, including posting of information or provision of access, the Site Administration recommends desisting from such actions.
<br />-V.III.- When using the Site the User is prohibited from:
<br />-V.III.I.- registering as the User on behalf of or instead of another person (“false account”) or registering a group (association) of persons or a legal entity as the User; however, the registration on behalf of another individual or legal entity is possible, if necessary powers are granted according to such procedure and form as provided by Spanish legislation;
<br />-V.III.II.- misleading other users as to his/her identity, using the login and password of another registered user;
<br />-V.III.III.- distorting information on his/her identity, age or relations with other persons or entities;
<br />-V.III.IV.- loading, storing, publishing, disseminating, making available or otherwise using any information which:
contains threats, discredits, insults, defiles honor, dignity or business reputation or violates the privacy of other Users or third parties;
infringes on the rights of minors;
is vulgar or obscene, contains pornographic images and texts or sexual scenes with the participation of minors;
contains scenes of inhumane treatment of animals;
describes means and methods of suicide, contains any instigation to commit suicide;
propagandizes and/or contributes to racial, religious, ethnic hatred or hostility, propagandizes fascism or racial superiority;
contains extremist materials;
propagandizes criminal activity or contains advices, instructions or guides for criminal activities;
contains restricted information including but not limited to government and trade secrets, information on the private life of third persons;
advertises or describes the attractiveness of using drugs, including “digital drugs” (audio files affecting the human brain through binaural rhythms), contains information on drug trafficking, drug recipes and drug consumption recommendations;
is of fraudulent nature;
or infringes other rights and interests of individuals and legal entities or requirements of Spanish legislation;
<br />-V.III.V.- illegally loading, storing, publishing, distributing, making available or otherwise using the intellectual property of other Users and third parties;
<br />-V.III.VI.- carrying out the mass mailing of messages without the Site Users’ consent;
<br />-V.III.VII.- using software and taking actions aimed at disrupting the normal operation of the Site and its services or the Users’ personal pages;
<br />-V.III.VIII.- loading, storing, publishing, distributing, making available or otherwise using viruses, trojans and other malicious software;
<br />-V.III.IX.- using automated scripts (programs) for collecting information on the Site and/or interacting with the Site and its services without specific permission of the Site Administration and its services;
<br />-V.III.X.- attempting to get access to another User’s login and passwords by any means including, without limitation, by means of fraud, abuse of confidence, cracking;
<br />-V.III.XI.- illegally collecting and processing the personal data of other persons;
<br />-V.III.XII.- accessing (attempting to access) any Services otherwise than via the interface provided by the Site Administration, unless such actions are expressly permitted for the User in accordance with a separate agreement with the Site Administration;
<br />-V.III.XIII.- reproducing, duplicating, copying, selling, dealing in and reselling the Services for any purposes, unless such actions are expressly permitted for the User in accordance with a separate agreement with the Site Administration;
<br />-V.III.XIV.- posting commercial and political advertisements outside the special Site sections as determined by the Site Administration; The User acquires paid services on the Site as provided in the special documents of the Site Administration available on the Site;
<br />-V.III.XV.- posting any other information which in the personal opinion of the Site Administration is undesirable, does not meet the Site purposes, infringes on the Users’ rights or is otherwise undesirable for posting on the Site.
<br />-V.IV.- The User bears personal responsibility for any information he/she posts on the Site or communicates to other Users as well as for any contacts with other Users on his/her own risk.
<br />-V.V.- In case the User disagrees with these Terms or their updates, the User must give up using the Site with a due notice to the Site Administration.</p>

<br /><p>VI.- Intellectual Rights
<br />-VI.I.- Exclusive rights in the Site Content
<br />-VI.I.I.- All objects placed on the Site, including design elements, text, graphic images, illustrations, scripts, software, music, sounds and other objects and their collections (hereinafter the Content) are subject to exclusive rights of the Site Administration, Users and other rights holders, all rights in these objects being reserved.
<br />-VI.I.II.- Except as provided by these Terms as well as by effective Spanish legislation, no Content may be copied (reproduced), processed, distributed, displayed in the frame, published, downloaded, transferred, sold or otherwise used in full or in part without the prior permission of the right owner, unless the right owner has expressly agreed to free use of the Content by any person.
<br />-VI.I.III.- By posting on the Site his/her lawfully owned Content, the User grants the other Users a non-exclusive right to use it by viewing, reproducing (including copying), processing (including printing of copies) and other rights exclusively for the purpose of personal non-commercial use, except where such use infringes or may infringe the right owner’s interests protected by law.
<br />-VI.I.IV.- The Content made available exclusively for the purpose of personal non-commercial use may be used by the User on the condition that all copyright marks or other authorship notices, name of the author and the work remain unchanged.
<br />-VI.I.V.- Except his/her own Content, the User does not have the right to upload or otherwise make available to the public (publish on the Site) the content of other sites, databases and other intellectual activity results without the express consent of the right owner.
<br />-VI.I.VI.- Any use of the Site or Content, except as permitted herein or except the right owner consents to such use in writing, without the prior written permission of the right owner is categorically prohibited.
<br />-VI.I.VII.- Unless otherwise expressly provided in these Terms, nothing in these Terms may be considered as the grant of exclusive rights in the Content.
<br />-VI.II.- Liability for the infringement of exclusive rights.
<br />-VI.II.I.- The User bears personal liability for any Content or other information he/she uploads or otherwise makes publicly available (publishes) on or via the Site. The User does not have the right to upload, transfer or publish Content on the Site unless he/she has appropriate rights to do so, such rights being acquired by or transferred to him/her in accordance with Spanish legislation.
<br />-VI.II.II.- The Site Administration has the right but is not obliged to check the Site for prohibited Content and can delete or remove (without giving advance notice) any Content or Users at its own discretion for any reason or without reason, including, without limitation, removal or deletion of the Content which, in the personal opinion of the Site Administration, infringes these Terms, Spanish legislation and/or may infringe the rights of, cause damage to, or threaten the security of other Users or third parties.
<br />-VI.II.III.- By posting his/her Content on the Site, the User grants the Site Administration the right to copy his/her Content in order to streamline and facilitate the publication and storage of the user Content on the Site.
<br />-VI.II.IV.- By posting his/her Content in any part of the Site, the User automatically grants the Site Administration free of charge the non-exclusive right to use it by copying, public performance, reproduction, processing, translation and distribution for or in connection with the purposes of the Site, including for the purpose of increasing its popularity. For these purposes, the Site Administration may produce derivative works or insert the User’s Content as components in relevant collections or take other actions for these purposes.
<br />-VI.II.V.- In case the User removes his/her Content from the Site, the rights mentioned in clauses VI.II.III. – VI.II.IV. hereof will be automatically cancelled; however, the Site Administration has the right to keep archive copies of the user Content for an indefinite period.
<br />-VI.III.- Third parties’ sites and content
<br />-VI.III.I.- The Site contains (or may contain) links to other web-sites (third parties’ sites) as well as articles, photos, illustrations, graphic images, music, sound, video, information, applications, software and other Content belonging to or originating from third parties (Third Parties’ Content), which is the result of intellectual activity and is protected in accordance with Spanish legislation.
<br />-VI.III.II.- The Site Administration does not check these third parties and their Content for conformity to any requirements (truthfulness, completeness, good faith etc.). The Site Administration does not bear liability for any information on third parties’ sites to which the User gains access via the Site or Third Parties’ Content, including any opinions or statements expressed on the Third Parties’ Sites or in their Content.
<br />-VI.III.III.- The fact that the Site contains links or instructions for downloading files and/or installing software of third parties does not mean that the Site Administration supports and approves of these actions.
<br />-VI.III.IV.- The fact that the Site contains a link or reference to any site, product, service, information of commercial or non-commercial nature does not mean that the Site Administration approves of or recommends the above.
<br />-VI.III.V.- If the User decides to leave the Site for the sites of third parties or use or install third parties’ software, he/she does it at his/her own risk and from this time these Terms do not apply to the User any longer. When taking further actions the User should follow the applicable standards and policies, including business practices of the persons whose Content he/she is going to use.</p>

<br /><p>VII.- "Diesel vs. Gasoline" Operation and Liability Regarding Use of the Site
<br />-VII.I.- The users bear liability for their own actions in connection with the creation and posting of information on their own personal page on the Site as well as in connection with the posting of information on the personal pages of other users and other sections of the Site in accordance with effective Spanish legislation. The breach of these Terms and effective Spanish legislation involves civil, administrative and criminal liability.
<br />-VII.II.- The Site Administration makes it technically possible for the Users to use the Site, does not participate in forming the content of the Users’ personal pages, does not control and does not bear liability for the actions or omissions of any persons regarding use of the Site or formation and use of the content of the Users’ personal pages on the Site.
<br />-VII.III.- The information system of the Site and its software do not contain any technical solutions for the automatic censorship and control of actions and information relations of the users regarding use of the Site.
<br />-VII.IV.- The Site Administration reserves the right to change at any time the Site design, content, list of services, modify or supplement scripts, software and other objects used or stored on the Site, any server applications at any time with or without advance notice.
<br />-VII.V.- The Site Administration does not carry out preliminary moderation or censorship of the Users’ information and takes actions to protect the rights and interests of persons and ensure compliance with the requirements of Spanish legislation only after the person concerned applies duly to the Site Administration.
<br />-VII.VI.- The Site Administration does not bear liability for the User’s breach of these Terms and reserves the right, at its own discretion as well as upon receipt of information from other Users or third parties on the User’s breach of these Terms, to modify (moderate) or remove any information published by the User in breach of the prohibitions set by these Terms (including personal messages), suspend, limit or terminate the User’s access to all or any sections or services of the Site at any time for any reason or without explaining the reason, with or without advance notice, without being liable for any damage that such action can cause to the User. The Site Administration reserves the right to remove the User’s personal page and/or suspend, limit or terminate the User’s access to any of the Site services, if the Site Administration believes that the User poses a threat to the Site and/or its Users. The Site Administration does not bear liability for temporarily blocking or removing information or removing the User’s personal page (registration termination) in accordance with these Terms.
<br />-VII.VII.- The removal of the User’s personal page means an automatic removal of all information posted on it as well as of all information entered by the User at the time of registration at the Site. After the personal page is removed, the User has no longer the right of access to the Site.
<br />-VII.VIII.- The Site Administration ensures operation and serviceability of the Site and undertakes to restore its serviceability promptly in case of technical failures and interruptions. The Site Administration does not bear liability for temporary failures and interruptions in the Site operation and resultant losses of information. The Site Administration does not bear liability for any damage to the computer of the User or any third party, mobile devices, any other equipment or software caused by or connected with the download of materials from the Site or via the links available on the Site.
<br />-VII.IX.- The Site Administration has the right to dispose of the statistical information relating to the Site operation as well as of the Users’ information to ensure the targeted display of advertising information to different audiences of Site users. For the purposes of operation and technical support of the Site and compliance with these Terms the Site Administration has the technical ability to access the Users’ personal pages but does it only in the cases specified herein.
<br />-VII.X.- The Site Administration has the right to send information on the development of the Site and its services to the User as well as to advertise its own activity and services.
<br />-VII.XI.- Limitation of the Site Administration’s liability:
THE SITE AND ITS SERVICES, INCLUDING ALL SCRIPTS, APPLICATIONS, CONTENT AND THE SITE DESIGN ARE MADE AVAILABLE ON THE “AS IS” BASIS. THE SITE ADMINISTRATION DISCLAIMS ALL WARRANTIES THAT THE SITE OR ITS SERVICES MAY BE SUITABLE OR UNSUITABLE FOR ANY SPECIFIC PURPOSES OF USE. THE SITE ADMINISTRATION CANNOT GUARANTEE AND DOES NOT PROMISE ANY SPECIFIC RESULTS OF USE OF THE SITE AND/OR ITS SERVICES.
FOR THE AVOIDANCE OF MISUNDERSTANDINGS, THE USER SHOULD BE CAREFUL WHEN DOWNLOADING FROM THE SITE OR VIA THE LINKS ON IT AND USING ANY FILES, INCLUDING SOFTWARE. THE SITE ADMINISTRATION STRONGLY RECOMMENDS USING ONLY LICENSED SOFTWARE, INCLUDING ANTIVIRUS SOFTWARE.
BY USING THE SITE THE USER AGREES THAT HE/SHE DOWNLOADS ANY MATERIALS FROM OR VIA THE SITE ON HIS/HER PERSONAL RISK AND BEARS PERSONAL LIABILITY FOR THE POSSIBLE CONSEQUENCES OF USING THESE MATERIALS, INCLUDING THE DAMAGE IT CAN CAUSE TO THE USER’S COMPUTER OR THIRD PARTIES, FOR DATA LOSS OR ANY OTHER DAMAGE.
UNDER NO CIRCUMSTANCES THE SITE ADMINISTRATION OR ITS REPRESENTATIVES BEAR LIABILITY TO THE USER OR ANY THIRD PARTIES FOR ANY INDIRECT, ACCIDENTAL, UNINTENTIONAL DAMAGE, INCLUDING LOST PROFIT OR LOST DATA, DAMAGE TO THE HONOR, DIGNITY OR BUSINESS REPUTATION IN CONNECTION WITH THE USE OF THE SITE, ITS CONTENT OR OTHER MATERIALS WHICH BECAME AVAILABLE TO THE USER OR OTHER PERSONS THROUGH THE SITE, EVEN IF THE SITE ADMINISTRATION HAS WARNED OF, OR INDICATED TO THE POSSIBILITY OF SUCH DAMAGE.</p>

<br /><p>VIII.- Closing provisions
<br />-VIII.I.- These Terms constitute the agreement between the User and the Site Administration concerning use of the Site and its services and supersede all previous agreements between the User and the Site Administration.
<br />-VIII.II.- These Terms are governed and construed in accordance with Spanish legislation. Those issues which are not settled by these Terms are subject to Spanish legislation.
<br />-VIII.III.- In case any disputes or differences arise in connection with the fulfillment of these Terms, the User and the Site Administration will make every effort to resolve these by negotiations. Those disputes which are not resolved by negotiations are to be resolved according to the procedure established by effective Spanish legislation.
<br />-VIII.IV.- These Terms become binding upon the User from the time of his/her accession and are valid during an indefinite period.
<br />-VIII.V.- These Terms are made in English and may be provided to the User for familiarization in another language. In case of discrepancies between the English and the foreign language versions of the Terms, the English language version will prevail.
<br />-VIII.VI.- In the event that one or more provisions hereof become invalid or unenforceable for any reason, this will not affect the validity or applicability of the remaining provisions.</p>
